name: Dump ACLs of cargo registry files

on: push

jobs:
  dump-acls:
    runs-on: windows-latest
    steps:

      - run: |
          $cargo_home = "$env:UserProfile\.cargo"
          $packdir = "$cargo_home\registry\index\github.com-1ecc6299db9ec823\.git\objects\pack"
          Get-Acl $packdir | Format-List
          Get-ChildItem $packdir |
          Foreach-Object { Get-Acl $_ | Format-List }
          $new_file = "$cargo_home\registry\foo"
          New-Item $new_file -ItemType "file"
          Get-Acl $new_file | Format-List
