on:
  push:
    branches:
      - master

env:
  GIT_AUTHOR_NAME: GitHub CI
  GIT_AUTHOR_EMAIL: 1198919+mzabaluev@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub CI
  GIT_COMMITTER_EMAIL: 1198919+mzabaluev@users.noreply.github.com

jobs:
  push:
    name: Test GitHub push on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git commit -m 'Test commit' --allow-empty
      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          branch: push-target
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
