name: Test tar behavior with read-only files

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - name: List read-only files
        run: Get-ChildItem .git -Recurse -Attributes ReadOnly

      - name: Pack and unpack
        run: |
          C:\windows\System32\tar.exe -cz -f ${{ runner.temp }}\repo.tgz .
          C:\windows\System32\tar.exe -xzv -f ${{ runner.temp }}\repo.tgz
