name: Test tar of the cargo repository index cache

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:

      - run: C:\windows\System32\tar.exe -cz -f ${{ runner.temp }}\index.tgz -C $env:UserProfile\.cargo\registry\index .

      - name: Unpack into the cargo index location
        run: C:\windows\System32\tar.exe -xzo -f ${{ runner.temp }}\index.tgz -C $env:UserProfile\.cargo\registry\index
