name: Test tar in the cargo registry index cache directory

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:

      - run: |
          $cache_dir = "$env:UserProfile\.cargo\registry\index"
          echo "Hello" > $cache_dir\file.txt
          C:\windows\System32\tar.exe -czv -f ${{ runner.temp }}\file.tgz -C $cache_dir file.txt
          C:\windows\System32\tar.exe -xzv -f ${{ runner.temp }}\file.tgz -C $cache_dir
