name: Test tar with the cargo registry index cache directory

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:

      - run: |
          $cache_dir = "C:\Rust\.cargo\registry\index\github.com-1ecc6299db9ec823\.git"
          Get-ChildItem $cache_dir -Recurse -Attributes ReadOnly
          C:\windows\System32\tar.exe -cz -f ${{ runner.temp }}\index.tgz -C $cache_dir .
          C:\windows\System32\tar.exe -tzv -f ${{ runner.temp }}\index.tgz
          C:\windows\System32\tar.exe -xz -f ${{ runner.temp }}\index.tgz -C $cache_dir
