name: Test tar of the cargo repository index cache

on: push

jobs:
  create-tar:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - run: cargo generate-lockfile

      - run: C:\windows\System32\tar.exe -cz -f ${{ runner.temp }}\index.tgz -C $env:UserProfile\.cargo\registry\index .

      - uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: ${{ runner.temp }}/index.tgz

  unpack-tar:
    needs: create-tar
    runs-on: windows-latest
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: tarball
          path: ${{ runner.temp }}

      - name: Unpack into the working directory
        run: C:\windows\System32\tar.exe -xz -f ${{ runner.temp }}\index.tgz

      - name: Unpack into the cargo index location
        run: C:\windows\System32\tar.exe -xz -f ${{ runner.temp }}\index.tgz -C $env:UserProfile\.cargo\registry\index
