on: push

jobs:
  fetch:
    strategy:
      matrix:
        os: [windows-latest]
        #os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: cargo-registry
        name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        id: ls-crates-io-index
        name: Get head commit hash of crates.io registry index
        continue-on-error: true
        shell: bash
        run: |
          commit=$(
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
            cut -f 1
          )
          echo "::set-output name=head::$commit"
      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        name: Cache cargo registry index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry/index
          key: crates.io-index-${{ steps.ls-crates-io-index.outputs.head }}
          restore-keys: |
            crates.io-index-
      - run: cargo fetch -vv --locked
      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        name: Prune unpacked sources of dependency crates from cache
        shell: bash
        run: |
          rm -rf ~/.cargo/registry/src
