name: Test tar on Windows

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:

      - run: echo "Hello" > file.txt

      - run: C:\windows\System32\tar.exe -czv -f ${{ runner.temp }}\file.tgz file.txt

      - run: C:\windows\System32\tar.exe -xzv -f ${{ runner.temp }}\file.tgz
